# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2.QtCore import (QCoreApplication, QMetaObject, QObject, QPoint,
    QRect, QSize, QUrl, Qt, QLocale, QDateTime, QTime, QDate)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor, QFont,
    QFontDatabase, QIcon, QLinearGradient, QPalette, QPainter, QPixmap,
    QRadialGradient)
from PySide2.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1400, 829)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame {    \n"
"    background-color: rgb(0, 85, 127);\n"
"    border-radius: 10px;\n"
"}")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setLineWidth(4)
        self.frame.setObjectName("frame")
        self.label = QLabel(self.frame)
        self.label.setGeometry(QRect(20, 20, 500, 261))
        self.label.setStyleSheet("QLabel{\n"
"background-color: rgb(186, 162, 27);\n"
"border-radius: 10px;\n"
"}")
        self.label.setFrameShape(QFrame.Box)
        self.label.setFrameShadow(QFrame.Raised)
        self.label.setLineWidth(2)
        self.label.setText("")
        self.label.setObjectName("label")
        self.handSign = QLabel(self.frame)
        self.handSign.setGeometry(QRect(20, 300, 1021, 491))
        self.handSign.setStyleSheet("QLabel{\n"
"background-color: rgb(165, 104, 93);\n"
"border-radius: 10px;\n"
"}")
        self.handSign.setFrameShape(QFrame.Box)
        self.handSign.setFrameShadow(QFrame.Raised)
        self.handSign.setLineWidth(2)
        self.handSign.setText("")
        self.handSign.setObjectName("handSign")
        self.label_3 = QLabel(self.frame)
        self.label_3.setGeometry(QRect(540, 20, 500, 261))
        self.label_3.setStyleSheet("QLabel{\n"
"background-color: rgb(186, 162, 27);\n"
"border-radius: 10px;\n"
"}")
        self.label_3.setFrameShape(QFrame.Box)
        self.label_3.setFrameShadow(QFrame.Raised)
        self.label_3.setLineWidth(2)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.timeEdit = QTimeEdit(self.frame)
        self.timeEdit.setGeometry(QRect(1070, 20, 291, 51))
        font = QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.timeEdit.setFont(font)
        self.timeEdit.setStyleSheet("QTimeEdit{\n"
"    font: 75 18pt \"Segoe UI\";\n"
"    background-color: rgb(85, 170, 127);\n"
"    border-radius: 10px;\n"
"}")
        self.timeEdit.setLocale(QLocale(QLocale.Korean, QLocale.SouthKorea))
        self.timeEdit.setFrame(False)
        self.timeEdit.setAlignment(Qt.AlignCenter)
        self.timeEdit.setReadOnly(True)
        self.timeEdit.setButtonSymbols(QAbstractSpinBox.NoButtons)
        self.timeEdit.setAccelerated(False)
        self.timeEdit.setMaximumDateTime(QDateTime(QDate(2022, 1, 1), QTime(23, 59, 59)))
        self.timeEdit.setMaximumDate(QDate(2022, 1, 1))
        self.timeEdit.setCurrentSection(QDateTimeEdit.AmPmSection)
        self.timeEdit.setCalendarPopup(False)
        self.timeEdit.setTimeSpec(Qt.LocalTime)
        self.timeEdit.setObjectName("timeEdit")
        self.label_2 = QLabel(self.frame)
        self.label_2.setGeometry(QRect(1070, 720, 291, 71))
        self.label_2.setStyleSheet("QLabel{\n"
"    font: 20pt \"Segoe UI\";\n"
"    background-color: rgb(170, 85, 127);\n"
"    border-radius: 10px;\n"
"}")
        self.label_2.setAlignment(Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.timeEdit.setDisplayFormat(_translate("MainWindow", "AP h:mm"))
        self.label_2.setText(_translate("MainWindow", "Warning: Cam1"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
