# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1457, 912)
        icon = QIcon()
        icon.addPixmap(QPixmap("../../../Pictures/web.png"), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setIconSize(QSize(24, 24))
        MainWindow.setToolButtonStyle(Qt.ToolButtonTextOnly)
        MainWindow.setAnimated(True)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QFrame(self.centralwidget)
        self.frame.setStyleSheet("QFrame {    \n"
"    background-color: rgb(0, 85, 127);\n"
"}")
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setLineWidth(4)
        self.frame.setObjectName("frame")
        self.situation1 = QLabel(self.frame)
        self.situation1.setGeometry(QRect(20, 30, 441, 331))
        self.situation1.setStyleSheet("QLabel{\n"
"background-color: rgb(186, 162, 27);\n"
"border-radius: 10px;\n"
"}")
        self.situation1.setFrameShape(QFrame.Box)
        self.situation1.setFrameShadow(QFrame.Raised)
        self.situation1.setLineWidth(2)
        self.situation1.setText("")
        self.situation1.setObjectName("situation1")
        self.handSign = QLabel(self.frame)
        self.handSign.setGeometry(QRect(20, 390, 700, 491))
        self.handSign.setStyleSheet("QLabel{\n"
"background-color: rgb(165, 104, 93);\n"
"border-radius: 10px;\n"
"}")
        self.handSign.setFrameShape(QFrame.Box)
        self.handSign.setFrameShadow(QFrame.Raised)
        self.handSign.setLineWidth(2)
        self.handSign.setText("")
        self.handSign.setObjectName("handSign")
        self.situation2 = QLabel(self.frame)
        self.situation2.setGeometry(QRect(490, 30, 451, 331))
        self.situation2.setStyleSheet("QLabel{\n"
"background-color: rgb(186, 162, 27);\n"
"border-radius: 10px;\n"
"}")
        self.situation2.setFrameShape(QFrame.Box)
        self.situation2.setFrameShadow(QFrame.Raised)
        self.situation2.setLineWidth(2)
        self.situation2.setText("")
        self.situation2.setObjectName("situation2")
        self.warning1 = QLabel(self.frame)
        self.warning1.setGeometry(QRect(750, 830, 671, 51))
        self.warning1.setStyleSheet("QLabel{\n"
"    font: 20pt \"Segoe UI\";\n"
"    background-color: rgb(170, 85, 127);\n"
"    border-radius: 10px;\n"
"}")
        self.warning1.setAlignment(Qt.AlignCenter)
        self.warning1.setObjectName("warning1")
        self.rccarCam = QLabel(self.frame)
        self.rccarCam.setGeometry(QRect(970, 30, 451, 331))
        self.rccarCam.setStyleSheet("QLabel{\n"
"background-color: rgb(186, 162, 27);\n"
"border-radius: 10px;\n"
"}")
        self.rccarCam.setFrameShape(QFrame.Box)
        self.rccarCam.setFrameShadow(QFrame.Raised)
        self.rccarCam.setLineWidth(2)
        self.rccarCam.setText("")
        self.rccarCam.setObjectName("rccarCam")
        self.droneCam = QLabel(self.frame)
        self.droneCam.setGeometry(QRect(750, 390, 451, 331))
        self.droneCam.setStyleSheet("QLabel{\n"
"background-color: rgb(186, 162, 27);\n"
"border-radius: 10px;\n"
"}")
        self.droneCam.setFrameShape(QFrame.Box)
        self.droneCam.setFrameShadow(QFrame.Raised)
        self.droneCam.setLineWidth(2)
        self.droneCam.setText("")
        self.droneCam.setObjectName("droneCam")
        self.warning2 = QLabel(self.frame)
        self.warning2.setGeometry(QRect(750, 750, 671, 51))
        self.warning2.setStyleSheet("QLabel{\n"
"    font: 20pt \"Segoe UI\";\n"
"    background-color: rgb(170, 85, 127);\n"
"    border-radius: 10px;\n"
"}")
        self.warning2.setAlignment(Qt.AlignCenter)
        self.warning2.setObjectName("warning2")
        self.pushButton = QPushButton(self.frame)
        self.pushButton.setGeometry(QRect(1230, 500, 191, 101))
        self.pushButton.setStyleSheet("QPushButton{\n"
"font: 75 18pt \"Segoe UI\";\n"
"background-color: rgb(103, 149, 255);\n"
"border-radius: 10px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QPushButton(self.frame)
        self.pushButton_2.setGeometry(QRect(1230, 620, 191, 101))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"font: 75 18pt \"Segoe UI\";\n"
"background-color: rgb(103, 149, 255);\n"
"border-radius: 10px;\n"
"}")
        self.pushButton_2.setAutoDefault(False)
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_7 = QLabel(self.frame)
        self.label_7.setGeometry(QRect(30, 10, 171, 21))
        self.label_7.setStyleSheet("QLabel{\n"
"    font: 16pt \"Segoe UI\";\n"
"    background-color: rgb(85, 170, 127);\n"
"}")
        self.label_7.setAlignment(Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.label_8 = QLabel(self.frame)
        self.label_8.setGeometry(QRect(500, 10, 171, 21))
        self.label_8.setStyleSheet("QLabel{\n"
"    font: 16pt \"Segoe UI\";\n"
"    background-color: rgb(85, 170, 127);\n"
"}")
        self.label_8.setAlignment(Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QLabel(self.frame)
        self.label_9.setGeometry(QRect(980, 10, 171, 21))
        self.label_9.setStyleSheet("QLabel{\n"
"    font: 16pt \"Segoe UI\";\n"
"    background-color: rgb(85, 170, 127);\n"
"}")
        self.label_9.setAlignment(Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.label_10 = QLabel(self.frame)
        self.label_10.setGeometry(QRect(30, 370, 171, 21))
        self.label_10.setStyleSheet("QLabel{\n"
"    font: 16pt \"Segoe UI\";\n"
"    background-color: rgb(85, 170, 127);\n"
"}")
        self.label_10.setAlignment(Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.label_11 = QLabel(self.frame)
        self.label_11.setGeometry(QRect(760, 370, 171, 21))
        self.label_11.setStyleSheet("QLabel{\n"
"    font: 16pt \"Segoe UI\";\n"
"    background-color: rgb(85, 170, 127);\n"
"}")
        self.label_11.setAlignment(Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.lcdNumber = QLCDNumber(self.frame)
        self.lcdNumber.setGeometry(QRect(1230, 390, 191, 91))
        self.lcdNumber.setStyleSheet("QLCDNumber{\n"
"background-color: rgb(208, 139, 0);\n"
"border-radius: 10px;\n"
"}")
        self.lcdNumber.setObjectName("lcdNumber")
        self.label_12 = QLabel(self.frame)
        self.label_12.setGeometry(QRect(1240, 370, 171, 21))
        self.label_12.setStyleSheet("QLabel{\n"
"    font: 16pt \"Segoe UI\";\n"
"    background-color: rgb(85, 170, 127);\n"
"}")
        self.label_12.setAlignment(Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.verticalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Handsign Project"))
        self.warning1.setText(_translate("MainWindow", "Warning: Situation1"))
        self.warning2.setText(_translate("MainWindow", "Warning: Situation2"))
        self.pushButton.setText(_translate("MainWindow", "On/Off\n"
"RC-CAR\n"
"Cam"))
        self.pushButton_2.setText(_translate("MainWindow", "On/Off\n"
"DRONE\n"
"Cam"))
        self.label_7.setText(_translate("MainWindow", "Situation1"))
        self.label_8.setText(_translate("MainWindow", "Situation2"))
        self.label_9.setText(_translate("MainWindow", "RC-CAR Cam"))
        self.label_10.setText(_translate("MainWindow", "Main Screen"))
        self.label_11.setText(_translate("MainWindow", "DRONE Cam"))
        self.label_12.setText(_translate("MainWindow", "Cases Solved"))


# if __name__ == "__main__":
#     import sys
#     app = QtWidgets.QApplication(sys.argv)
#     MainWindow = QtWidgets.QMainWindow()
#     ui = Ui_MainWindow()
#     ui.setupUi(MainWindow)
#     MainWindow.show()
#     sys.exit(app.exec_())
